#!/bin/sh

# source library functions
source "$HOME/.config/bspwm/bspwmrc.functions"

# source before config
source "$HOME/.config/bspwm/bspwmrc.before"

# set an external monitor which takes precedence if detected
if [ $external_main ] && [ "$(xrandr | grep "^$external_main connected")" ];
then
	xrandr --output $external_main --left-of $internal --auto
	MAIN_MONITOR="$external_main"
else
	MAIN_MONITOR=$internal
fi

sxhkd -c $HOME/.config/sxhkd/sxhkdrc $HOME/.config/sxhkd/sxhkdrc.bspwm $HOME/.config/sxhkd/sxhkdrc.host &
autorandr -c &
nitrogen --restore &

reset_desktops "$MAIN_MONITOR"


bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus true
bspc config pointer_modifier mod4
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

# external rule command
bspc config external_rules_command ~/.local/bin/autonamer.sh

# use '^NUMBER' to select via desktop number
# WM_CLASS:WM_INSTANCE, this is reverse to wmctrl -lx
bspc rule -a Firefox:Navigator focus=on follow=on
bspc rule -a st-256color -o focus=on follow=on
bspc rule -a Thunderbird focus=on follow=on
bspc rule -a keepassxc desktop='Keepass' -o
bspc rule -a Zim focus=on follow=on
bspc rule -a Telegram focus=on follow=on
bspc rule -a \*:libreoffice focus=on follow=on state=tiled
bspc rule -a Steam focus=on follow=on
bspc rule -a Soffice state=tiled

bspc rule -a Chromium:chromium focus=on follow=on
bspc rule -a Chromium:crx_nckgahadagoaajjgafhacjanaoiihapd focus=on follow=on # Hangouts extension

bspc rule -a Xfce4-appfinder state=floating

bspc rule -a Emacs state=tiled focus=on follow=on
bspc rule -a \*:qmlscene state=floating


# remove the large x
xsetroot -cursor_name left_ptr

eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

# start xfce4-notifyd as notification handler simply by installing it
redshift &
ibus-daemon -drx &
nextcloud &
$HOME/.config/polybar/launch.sh $MAIN_MONITOR &
keepassxc &
lxqt-policykit-agent &
xfce4-clipman &

# after file for starting specific applications, overriding config etc
source "$HOME/.config/bspwm/bspwmrc.after"
