call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'altercation/vim-colors-solarized'
Plug 'chriskempson/base16-vim'
Plug 'jamessan/vim-gnupg'
" Plug 'scrooloose/syntastic' " external dependencies needed for each language
" Plug 'fholgado/minibufexpl.vim'
" somehow sensible tagging, will need ctags installed
Plug 'majutsushi/tagbar'
Plug 'xolox/vim-misc', { 'for' : ['python', 'c', 'cpp'] }
Plug 'xolox/vim-easytags', { 'for' : ['python', 'c', 'cpp'] }
set tags=./tags
let g:easytags_dynamic_files = 1
" autocompletion, might need to be recompiled
" Plug 'Shougo/neocomplete.vim'
Plug 'ervandew/supertab'
" Plug 'klen/python-mode', { 'for' : 'python' }
Plug 'vim-latex/vim-latex', { 'for': 'tex' }
" Plugins for c/c++ programming
" cvim plugin code checking needs eg splint, cppcheck
Plug 'WolfgangMehner/vim-plugins', {'for': ['c', 'cpp']}
Plug 'scrooloose/syntastic', {'for': ['c', 'cpp']}
"lisp plugins
Plug 'kovisoft/slimv', { 'for' : 'lisp' }
" vimwiki plugin for personal wiki
Plug 'vimwiki/vimwiki'
Plug 'mattn/calendar-vim'

"better status
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
let g:airline_theme='solarized'
Plug 'rust-lang/rust.vim'

so ~/.vimrc.local
let mapleader=","
let g:calendar_monday = 1
" autocmd FileType vimwiki map d :VimwikiMakeDiaryNote
" function! ToggleCalendar()
"   execute ":Calendar"
"   if exists("g:calendar_open")
"     if g:calendar_open == 1
"       execute "q"
"       unlet g:calendar_open
"     else
"       g:calendar_open = 1
"     end
"   else
"     let g:calendar_open = 1
"   end
" endfunction
" autocmd FileType vimwiki map c :call ToggleCalendar()<CR>


" special neovim plugins
if has('nvim')
	Plug 'Shougo/deoplete.nvim'
	Plug 'zchee/deoplete-jedi', { 'for' : 'python' }
	Plug 'Rip-Rip/clang_complete', {'for': ['c', 'cpp']}
	let g:deoplete#enable_at_startup = 1
	" set up neovim keybinds
	tnoremap <Esc> <C-\><C-n>
	tnoremap <A-h> <C-\><C-n><C-w>h
	tnoremap <A-j> <C-\><C-n><C-w>j
	tnoremap <A-k> <C-\><C-n><C-w>k
	tnoremap <A-l> <C-\><C-n><C-w>l
	nnoremap <A-h> <C-w>h
	nnoremap <A-j> <C-w>j
	nnoremap <A-k> <C-w>k
	nnoremap <A-l> <C-w>l
	" config easytag for better performance
	let g:easytags_async = 1
else
	Plug 'davidhalter/jedi-vim', { 'for' : 'python' }
	Plug 'justmao945/vim-clang', {'for': ['c', 'cpp']}
endif
call plug#end()
"other default settings
set nocompatible
syntax on
filetype plugin indent on
set number
set ignorecase smartcase " only case sensitive when using uppercase
set mouse=a
"setup wordwrap
set wrap linebreak nolist formatoptions-=t breakindent
"set colorscheme for gvim
let base16colorspace=256
colorscheme base16-tomorrow
if has("gui_running")
	set background=light
	set guioptions-=r
	set guioptions-=T
	set lines=46 columns=90
	set guifont=Terminus\ 12
	autocmd GUIEnter * set visualbell t_vb=
else
	set background=dark
endif
"no beeping
set vb t_vb=

""" Keyboard remaps
"tagbar toggle
nmap <F8> :TagbarToggle<CR>
"minibufexpl mappings
map <Leader>mbe :MBEOpen<cr>
map <Leader>mbc :MBEClose<cr>
map <Leader>mbt :MBEToggle<cr>
"setup arrowkeys for visual scroll
noremap  <buffer> <silent> <Up>   gk
noremap  <buffer> <silent> <Down> gj
noremap  <buffer> <silent> <Home> g<Home>
noremap  <buffer> <silent> <End>  g<End>
inoremap <buffer> <silent> <Up>   <C-o>gk
inoremap <buffer> <silent> <Down> <C-o>gj
inoremap <buffer> <silent> <Home> <C-o>g<Home>
inoremap <buffer> <silent> <End>  <C-o>g<End>

"put swap files in own folder
set backupdir=~/.local/share/vim/backup//
set directory=~/.local/share/vim/swap//
set undodir=~/.local/share/vim/undo//

