call plug#begin() 
" Plug 'tpope/vim-sensible'
Plug 'chriskempson/base16-vim'
Plug 'Yggdroot/indentLine'
let g:indentLine_char = '┆'

" autocompletion, might need to be recompiled
Plug 'ervandew/supertab'

" vimwiki plugin for personal wiki
Plug 'vimwiki/vimwiki'
Plug 'mattn/calendar-vim'
let g:calendar_monday = 1

" airline status
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
let g:airline#extensions#tabline#enabled = 1
" do not show the insert status, since we already have airline
set noshowmode

so ~/.vimrc.local
let mapleader=","

" backup files
set backup
" undo history persistent after closed file
set undofile

" special neovim plugins
if has('nvim')
	function! DoRemote(arg)
		UpdateRemotePlugins
	endfunction

	Plug 'Shougo/deoplete.nvim', { 'do': function('DoRemote') }
	Plug 'zchee/deoplete-jedi', { 'for' : 'python' }
	let g:deoplete#enable_at_startup = 1
	let g:deoplete#ignore_sources = {'_': ['buffer','tag']}
	Plug 'Shougo/neco-vim', { 'for' : 'vim' }

	" set up neovim keybinds
	tnoremap <Esc> <C-\><C-n>
	tnoremap <A-h> <C-\><C-n><C-w>h
	tnoremap <A-j> <C-\><C-n><C-w>j
	tnoremap <A-k> <C-\><C-n><C-w>k
	tnoremap <A-l> <C-\><C-n><C-w>l
	nnoremap <A-h> <C-w>h
	nnoremap <A-j> <C-w>j
	nnoremap <A-k> <C-w>k
	nnoremap <A-l> <C-w>l
else
	set nocompatible
endif
call plug#end()

" color trailing whitespace
highlight ExtraWhitespace ctermbg=red
match ExtraWhitespace /\s\+$\|\t/

syntax on

" indentation settings
filetype plugin indent on
set autoindent
" smart tabs configuration - use tabs for indent and spaces for align
set noexpandtab copyindent preserveindent softtabstop=0 shiftwidth=4 tabstop=4

set number
set ignorecase smartcase " only case sensitive when using uppercase
set mouse=a
" setup wordwrap
set wrap linebreak list formatoptions-=t breakindent

" set colorscheme for urxvt-256colors
if $TERM =~ '256color'
	let base16colorspace=256
	colorscheme base16-tomorrow-night
	set background=dark
	let g:airline_theme='base16'
endif
" no beeping
set vb t_vb=

" setup arrowkeys for visual scroll
noremap  <buffer> <silent> <Up>   gk
noremap  <buffer> <silent> <Down> gj
noremap  <buffer> <silent> <Home> g<Home>
noremap  <buffer> <silent> <End>  g<End>
inoremap <buffer> <silent> <Up>   <C-o>gk
inoremap <buffer> <silent> <Down> <C-o>gj
inoremap <buffer> <silent> <Home> <C-o>g<Home>
inoremap <buffer> <silent> <End>  <C-o>g<End>

" remove highlight with escape in normal mode
nnoremap <esc> :noh<return><esc>
nnoremap <esc>^[ <esc>^[

" german remaps for easier movements
nnoremap ö (
vnoremap ö (
xnoremap ö (
snoremap ö (
nnoremap ä )
vnoremap ä )
xnoremap ä )
snoremap ä )
nnoremap Ö {
vnoremap Ö {
xnoremap Ö {
snoremap Ö {
nnoremap Ä }
vnoremap Ä }
xnoremap Ä }
snoremap Ä }
nnoremap ü <C-]>
