#!/bin/bash
set -e
set -u

workdir="/home/max/Gits/Configurations/Goodies"
primary="LVDS1"
intdriver="Intel"
extdriver="modesetting"
providernumber=$( xrandr --listproviders | grep number | grep -o '[0-9]*' )
extgpu=$( xrandr --listproviders | grep $extdriver | grep -o '^Provider [0-9]*' | awk '{print $2 }' )
intgpu=$( xrandr --listproviders | grep $intdriver | grep -o '^Provider [0-9]*' | awk '{print $2 }' )
if (( $providernumber >= 2 )) && [[ -n $extgpu ]]; then
	echo "Setting up external gpu"
	xrandr --setprovideroutputsource $extgpu $intgpu
fi

output=$(xrandr | grep -m 1 'DVI.* connected' | awk '{print $1 }')
if [ -z $output ]; then
	echo "No connected DVI-Device found. Either no displaylink device has been connected, or the device has not been activated properly."
	exit 1
fi

if ! xrandr | grep -q "1280x960_95"; then
	echo $output
	echo "No mode detected, adding mode to external display output"
	"$workdir"/eizo_setup.sh "$output"
else
	"$workdir"/eizo_setup.sh "$output" first
fi
xrandr --output $output --mode "1280x960_95.00" --auto --left-of $primary
echo "Configuring output layout for docking station usage."
notify-send -t 10 "Setting up displaylink"
