# local bin path
export PATH=~/.local/bin:.:$PATH

export GPG_AGENT_INFO=""

# ibus exports
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

# disable symlink generation by wine
export WINEDLLOVERRIDES="winemenubuilder.exe=d"

# virtualenvwrapper settings
export WORKON_HOME=~/.virtualenvs
export PROJECT_HOME=$HOME/PyDevel
source /usr/bin/virtualenvwrapper.sh

# rust cargo path
export PATH="$HOME/.cargo/bin:$PATH"

# configure qt5 apps with qt5ct
export QT_QPA_PLATFORMTHEME=qt5ct

# ruby gems
PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"
export GEM_HOME=$(ruby -e 'print Gem.user_dir')

# nodejs
PATH="$HOME/.node_modules/bin:$PATH"
export npm_config_prefix=~/.node_modules
